### ISSUE TITLE
I would consider to use consistent naming practices

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#1]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/src/Command/ImportCommand.php#L24

More info about practices we used on daily basis:

https://www.php-fig.org/psr/psr-1/ and https://www.php-fig.org/psr/psr-12/

**Comment by wkorol** [comment]
Fixed
