### ISSUE TITLE
Add abstraction layer for fetching valid provider

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#11]
https://github.com/wkorol/vcs-import-project/blob/cafd0006677ff133e105993fe056e5385a77d17b/src/Command/ImportCommand.php#L53-L65

That code can be change to something like (pseudocode):

```php
$importCommand = $this->importCommandCreator->create($input->getArgument('username'), $input->getArgument('provider'));
$this->bus->dispatch($importCommand);
```

ImportCommandCreator can be implemented for example using abstract factory pattern https://designpatternsphp.readthedocs.io/en/latest/Creational/AbstractFactory/README.html to returns Concrete implementation of ImportCommand (for example GithubImportCommand). 

Those commands should be dispatcher into Bus from the messager https://symfony.com/doc/current/messenger.html#dispatching-the-message (we need to inject Symfony\Component\Messenger\MessageBusInterface in the constructor for our symfony CLI command). Then we can have separate GithubImportCommandHandler and BitbucketImportCommandHandler

**Comment by wkorol** [comment]
Solved
