### ISSUE TITLE
Please rethink design and architecture of the command which use Controller as dependency

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#2]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/src/Command/ImportCommand.php#L22

Use controller which most of the time works in the scope of http request can cause potential problems. In scope of command we do not have request etc. The best way of handle such stuff is delegate work into some kind of service so Controller will use that service and Command will use same service. Service is in separate layer independent from the UI layer (in one case UI layer is command line CLI in other HTTP controller) so we be reused (injected using Dependecy Injection mechanism in Symfony) in Controller and in the Command

**Comment by wkorol** [comment]
Fixed
