### ISSUE TITLE
Please try to avoid nested conditions if that would be possible

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#3]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/src/Command/ImportCommand.php#L45-L53

I always try (of course if not always good or one "right" way) to do such exercise with code https://williamdurand.fr/2013/06/03/object-calisthenics/ that will often cause that in the end code is more readable :) Please be aware that code formatting and readability is for human beings computer does not care about format and structure of code (and to be honest we use some obfuscation mechanism to do code size smaller so for the computer it can be even better sometimes ;) ) - in the end it is compiled into some byte code and binary code :)

**Comment by wkorol** [comment]
Fixed
