### ISSUE TITLE
Please use higher level tooling for such stuff as reading from external API

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#4]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/src/Controller/GithubController.php#L38-L48

Good that you know curl stuff from PHP, but we have more sophisticated tools right now we even allow use to change implementation under the hood, and use stuff like async fetching of http messages https://symfony.com/doc/current/http_client.html it more friendly for developer and it easier to unit test such stuff.

**Comment by wkorol** [comment]
Fixed, now httpClient is included into the project.
