### ISSUE TITLE
Whole .idea directory should not be in repository as other developers can have different setting 

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#8]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/.idea/php.xml#L1

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000154070-How-to-gitignore-idea-files
https://stackoverflow.com/questions/59328900/how-to-globally-ignore-the-idea-folder-in-git-not-just-adding-it-to-gitignor

**Comment by wkorol** [comment]
Fixed
