### ISSUE TITLE
Will be good to use docker and docker-compose if you have it in project

### ISSUE THREAD

**Issue by l3l0** [wkorol/vcs-import-project#9]
https://github.com/wkorol/vcs-import-project/blob/0bd204790f3b1a327820ce52f7d6b1a3b5e95ff7/docker-compose.yml#L1

In README you have wrote that we need to setup mysql database in docker compose you have postgres. I suppose it is generated by symfony itself. We use docker a lot so maybe it be actually good idea to try use it.

https://symfony.com/doc/current/setup/docker.html

**Comment by wkorol** [comment]
Fixed.
